/**
 * dsh-cursor-theme built-in asset catalog (M3a).
 *
 * Loaded from data/assets.json (generated by scripts/generate-assets.mjs)
 * and bundled into client/client.js by esbuild (JSON import). Each asset is
 * a ready-to-use data URL with its recommended hotspot and target state.
 */

import assetsJson from '../../data/assets.json'

export interface BuiltinAsset {
  id: string
  name: string
  /** State ids this asset is designed for. */
  states: string[]
  /** Recommended CSS fallback keyword for this shape. */
  fallback: string
  /** Recommended hotspot {x, y}. */
  hotspot: { x: number; y: number }
  /** Display size in px. */
  size: number
  /** data: URL image. */
  image: string
}

export const BUILTIN_ASSETS: BuiltinAsset[] = (assetsJson as { assets: BuiltinAsset[] }).assets

/** Assets usable for a given state (by shape name match, else all). */
export function assetsForState(stateId: string): BuiltinAsset[] {
  const exact = BUILTIN_ASSETS.filter((a) => a.states.includes(stateId))
  return exact.length > 0 ? exact : BUILTIN_ASSETS
}
