/**
 * dsh-cursor-theme built-in template catalog (M5).
 *
 * Loaded from data/assets.json (generated by scripts/generate-assets.mjs).
 * Exposes the SVG shape templates so the editor's built-in picker can offer
 * per-state shapes (rendered with the active theme palette or standalone).
 */

import assetsJson from '../../data/assets.json'

export interface BuiltinAsset {
  id: string
  name: string
  /** State ids this asset is designed for. */
  states: string[]
  /** Recommended CSS fallback keyword. */
  fallback: string
  /** Recommended hotspot {x, y}. */
  hotspot: { x: number; y: number }
  /** Display size in px. */
  size: number
  /** SVG artwork with {primary}/{accent}/{dark} placeholders. */
  svg: string
}

export const BUILTIN_ASSETS: BuiltinAsset[] = (assetsJson as { assets?: BuiltinAsset[]; templates: BuiltinAsset[] }).templates

/** Templates usable for a given state. */
export function assetsForState(stateId: string): BuiltinAsset[] {
  const exact = BUILTIN_ASSETS.filter((a) => a.states.includes(stateId))
  return exact.length > 0 ? exact : BUILTIN_ASSETS
}
